### ISSUE TITLE
Unclosed quotation marks causes panic

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#259]
Checked with REPL and normal execution. (Checked with master branch as well)

* The following causes panic:

```ruby
» a = "bb""
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/goby-lang/goby/compiler/lexer.(*Lexer).readString(0xc42012b4c0, 0xc420081622, 0xc4200816d0, 0x0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/lexer/lexer.go:306 +0x147
github.com/goby-lang/goby/compiler/lexer.(*Lexer).NextToken(0xc42012b4c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/lexer/lexer.go:49 +0x49b
github.com/goby-lang/goby/compiler/parser.(*Parser).nextToken(0xc420012c00)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/parser/parser.go:192 +0x72
github.com/goby-lang/goby/compiler/parser.(*Parser).parseInfixExpression(0xc420012c00, 0x1510c80, 0xc42012b540, 0x2, 0x0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/parser/expression_parsing.go:316 +0x112
github.com/goby-lang/goby/compiler/parser.(*Parser).(github.com/goby-lang/goby/compiler/parser.parseInfixExpression)-fm(0x1510c80, 0xc42012b540, 0x1396f85, 0x1)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/parser/parser.go:118 +0x3e
github.com/goby-lang/goby/compiler/parser.(*Parser).parseExpression(0xc420012c00, 0x1, 0x13976de, 0x5)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/parser/expression_parsing.go:117 +0x1cf
github.com/goby-lang/goby/compiler/parser.(*Parser).parseExpressionStatement(0xc420012c00, 0x5)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/parser/statement_parsing.go:170 +0xa4
github.com/goby-lang/goby/compiler/parser.(*Parser).parseStatement(0xc420012c00, 0x155aa38, 0x1)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/parser/statement_parsing.go:12 +0x234
github.com/goby-lang/goby/compiler/parser.(*Parser).ParseProgram(0xc420012c00, 0x9, 0xc42012b4c0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/parser/parser.go:155 +0xef
github.com/goby-lang/goby/igb.StartIgb(0x1397639, 0x5)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/igb/repl.go:118 +0x738
main.main()
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/goby.go:27 +0x657
```

* The following behaves as if the quotation is implicitly closed on the end of line 1. 

```ruby
» a = "1
#=>
» a
#=> 1
```

The behaviors should be fixed on normal execution and REPL.

(Ruby treats both of them as the quotation is not closed)

**Comment by st0012** [comment]
@hachi8833 Currently I just ignore the content in unclosed string, it's not a very ideal way but can prevent panicking.

**Comment by st0012** [comment]
I'll close it since it won't panic anymore. And we should create a new one if we want to change current behavior.
