### ISSUE TITLE
Panic on Index Value Out of Range When Input is *RClass Type

### ISSUE THREAD

**Issue by Maxwell-Alexius** [goby-lang/goby#279]
I found out that when **successively input only `*RClass` type**(which is `Class` type in Goby) , it will panic which states that `index value out of range`. For instance:

```
$ go run goby.go -i
Goby 0.0.9
» "1234567890".include "123"
#=> true
» "1234567890".include "123", Class
ArgumentError: Expect 1 argument. got=2
#=> ERROR: ArgumentError: Expect 1 argument. got=2
» "1234567890".include "123", Class, Integer
Internal Error: runtime error: index out of range
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 1 [running]:
github.com/goby-lang/goby/vm.(*thread).execInstruction.func1(0xc42012b1d0)
        /Users/MaxwellAlexius/go/src/github.com/goby-lang/goby/vm/thread.go:71 +0x81
panic(0x1336140, 0x15392a0)
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/goby-lang/goby/vm.glob..func21(0xc42012b1d0, 0xc4201f6310, 0xc42013e4e0, 0x2, 0x2)
        /Users/MaxwellAlexius/go/src/github.com/goby-lang/goby/vm/instruction.go:343 +0x452
github.com/goby-lang/goby/vm.(*thread).execInstruction(0xc42012b1d0, 0xc4201f6310, 0xc420157560)
        /Users/MaxwellAlexius/go/src/github.com/goby-lang/goby/vm/thread.go:75 +0x96
github.com/goby-lang/goby/vm.(*thread).evalCallFrame(0xc42012b1d0, 0xc4201f6310)
        /Users/MaxwellAlexius/go/src/github.com/goby-lang/goby/vm/thread.go:42 +0x60
github.com/goby-lang/goby/vm.(*thread).startFromTopFrame(0xc42012b1d0)
        /Users/MaxwellAlexius/go/src/github.com/goby-lang/goby/vm/thread.go:36 +0x55
github.com/goby-lang/goby/vm.(*VM).startFromTopFrame(0xc42010a480)
        /Users/MaxwellAlexius/go/src/github.com/goby-lang/goby/vm/vm.go:190 +0x2f
github.com/goby-lang/goby/vm.(*VM).REPLExec(0xc42010a480, 0xc42013e420, 0x3, 0x4)
        /Users/MaxwellAlexius/go/src/github.com/goby-lang/goby/vm/repl.go:42 +0x64e
github.com/goby-lang/goby/igb.StartIgb(0x139a4df, 0x5)
        /Users/MaxwellAlexius/go/src/github.com/goby-lang/goby/igb/repl.go:212 +0xfed
main.main()
        /Users/MaxwellAlexius/go/src/github.com/goby-lang/goby/goby.go:27 +0x657
exit status 2
```

In the example, it should output:

```
#=> ERROR: ArgumentError: Expect 1 argument. got=3
```

I found out that the problem is in the `vm/instruction.go:343` which:

```go
	bytecode.Send: {
		name: bytecode.Send,
		operation: func(t *thread, cf *callFrame, args ...interface{}) {
			var method Object

			methodName := args[0].(string)
			argCount := args[1].(int)
			argPr := t.sp - argCount
			receiverPr := argPr - 1
			receiver := t.stack.Data[receiverPr].Target
```

the `receiverPr` is `-1`. Any advice to solve this?

**Comment by Maxwell-Alexius** [comment]
Another case is that **the receiver and the first argument** are `*RClass` type, it will also cause the same panic stated above. For instance:

```go
$ go run goby.go -i
Goby 0.0.9
» Integer.class String
Internal Error: runtime error: index out of range
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 1 [running]:
github.com/goby-lang/goby/vm.(*thread).execInstruction.func1(0xc420123500)
        /Users/MaxwellAlexius/go/src/github.com/goby-lang/goby/vm/thread.go:71 +0x81
panic(0x1336140, 0x15392a0)
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/goby-lang/goby/vm.glob..func21(0xc420123500, 0xc420145340, 0xc42014e240, 0x2, 0x2)
        /Users/MaxwellAlexius/go/src/github.com/goby-lang/goby/vm/instruction.go:343 +0x452
github.com/goby-lang/goby/vm.(*thread).execInstruction(0xc420123500, 0xc420145340, 0xc420142750)
        /Users/MaxwellAlexius/go/src/github.com/goby-lang/goby/vm/thread.go:75 +0x96
github.com/goby-lang/goby/vm.(*thread).evalCallFrame(0xc420123500, 0xc420145340)
... Rest of the errors omitted ...
exit status 2
```

However, once again, if there are successive input of `*RClass` object in program, it cause the same panic:

```go
$ go run goby.go -i
Goby 0.0.9
» Integer.class 1
#=> <Class:Class>
» Integer.class 1, Hash
#=> <Class:Class>
» Integer.class 1, Hash, String
Internal Error: runtime error: index out of range
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 1 [running]:
github.com/goby-lang/goby/vm.(*thread).execInstruction.func1(0xc420123470)
        /Users/MaxwellAlexius/go/src/github.com/goby-lang/goby/vm/thread.go:71 +0x81
panic(0x1336140, 0x15392a0)
        /usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/goby-lang/goby/vm.glob..func21(0xc420123470, 0xc42015df80, 0xc42018a500, 0x2, 0x2)
        /Users/MaxwellAlexius/go/src/github.com/goby-lang/goby/vm/instruction.go:343 +0x452
github.com/goby-lang/goby/vm.(*thread).execInstruction(0xc420123470, 0xc42015df80, 0xc42015aff0)
        /Users/MaxwellAlexius/go/src/github.com/goby-lang/goby/vm/thread.go:75 +0x96
github.com/goby-lang/goby/vm.(*thread).evalCallFrame(0xc420123470, 0xc42015df80)
... Rest of the errors omitted ...
exit status 2
```

**Comment by hachi8833** [comment]
Looks like you need Stan's help. @st0012

**Comment by st0012** [comment]
@Maxwell-Alexius See #280
