### ISSUE TITLE
Invalid instance variable causes panic

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#287]
Note that the placement of instance variable `@inst` is meaningless and invalid.
Ruby just ignores the invalid `@inst = 1`. I wonder if Goby should warn this or not.

```ruby
» class Bar
*   @inst = 1
» end
Internal Error: interface conversion: vm.Object is *vm.RClass, not *vm.RObject
panic: interface conversion: vm.Object is *vm.RClass, not *vm.RObject [recovered]
	panic: interface conversion: vm.Object is *vm.RClass, not *vm.RObject [recovered]
	panic: interface conversion: vm.Object is *vm.RClass, not *vm.RObject

goroutine 1 [running]:
github.com/goby-lang/goby/vm.(*thread).execInstruction.func1(0xc420143050)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:71 +0x81
panic(0x1338600, 0xc4202c8c80)
	/usr/local/opt/go/libexec/src/runtime/panic.go:489 +0x2cf
github.com/goby-lang/goby/vm.(*thread).execInstruction.func1(0xc420143050)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:71 +0x81
panic(0x1338600, 0xc4202c8c80)
	/usr/local/opt/go/libexec/src/runtime/panic.go:489 +0x2cf
github.com/goby-lang/goby/vm.glob..func6(0xc420143050, 0xc42036e150, 0xc42036c530, 0x1, 0x1)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/instruction.go:107 +0x144
github.com/goby-lang/goby/vm.(*thread).execInstruction(0xc420143050, 0xc42036e150, 0xc420370960)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:75 +0x96
github.com/goby-lang/goby/vm.(*thread).evalCallFrame(0xc420143050, 0xc42036e150)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:42 +0x60
github.com/goby-lang/goby/vm.(*thread).startFromTopFrame(0xc420143050)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:36 +0x55
github.com/goby-lang/goby/vm.glob..func20(0xc420143050, 0xc42036e0e0, 0xc42036c560, 0x1, 0x1)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/instruction.go:334 +0x268
github.com/goby-lang/goby/vm.(*thread).execInstruction(0xc420143050, 0xc42036e0e0, 0xc420370a20)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:75 +0x96
github.com/goby-lang/goby/vm.(*thread).evalCallFrame(0xc420143050, 0xc42036e0e0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:42 +0x60
github.com/goby-lang/goby/vm.(*thread).startFromTopFrame(0xc420143050)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:36 +0x55
github.com/goby-lang/goby/vm.(*VM).startFromTopFrame(0xc4200242d0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/vm.go:190 +0x2f
github.com/goby-lang/goby/vm.(*VM).REPLExec(0xc4200242d0, 0xc420196500, 0xb, 0x10)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/repl.go:42 +0x64e
github.com/goby-lang/goby/igb.StartIgb(0x139a27b, 0x5)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/igb/repl.go:215 +0x152f
main.main()
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/goby.go:27 +0x657
```

**Comment by st0012** [comment]
I think I'll block this kind of usage during parsing.

**Comment by st0012** [comment]
@hachi8833 I thought that class should be able to have instance variables, so I won't block this kind of behavior. And you can see the commit that closes this issue has some test about it.
