### ISSUE TITLE
Assignments in argument of `puts()` causes panic

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#297]
FYI: `puts(a == 10)` works.

```ruby
» a = 10
#=>
» puts(a = 10)
Internal Error: runtime error: index out of range
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 1 [running]:
github.com/goby-lang/goby/vm.(*thread).execInstruction.func1(0xc420145cb0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:71 +0x81
panic(0x43d5500, 0x462f0e0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:489 +0x2cf
github.com/goby-lang/goby/vm.glob..func21(0xc420145cb0, 0xc420164a10, 0xc420162180, 0x2, 0x2)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/instruction.go:348 +0x4ae
github.com/goby-lang/goby/vm.(*thread).execInstruction(0xc420145cb0, 0xc420164a10, 0xc4201684e0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:75 +0x96
github.com/goby-lang/goby/vm.(*thread).evalCallFrame(0xc420145cb0, 0xc420164a10)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:42 +0x60
github.com/goby-lang/goby/vm.(*thread).startFromTopFrame(0xc420145cb0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:36 +0x55
github.com/goby-lang/goby/vm.(*VM).startFromTopFrame(0xc420024750)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/vm.go:192 +0x2f
github.com/goby-lang/goby/vm.(*VM).REPLExec(0xc420024750, 0xc42016a240, 0x2, 0x2)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/repl.go:42 +0x64e
github.com/goby-lang/goby/igb.StartIgb(0x443fcc9, 0x5)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/igb/repl.go:218 +0x1606
main.main()
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/goby.go:27 +0x657
```

**Comment by hachi8833** [comment]
Another pattern:

```ruby
» require("file")
#=> true
» puts(File.extname "test.gb")
Internal Error: runtime error: index out of range
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 1 [running]:
github.com/goby-lang/goby/vm.(*thread).execInstruction.func1(0xc420155cb0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:71 +0x81
panic(0x43d5500, 0x462f0e0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:489 +0x2cf
github.com/goby-lang/goby/vm.builtinFileClassMethods.func5.1(0xc420155cb0, 0x4655c00, 0x0, 0x0, 0x0, 0xc42023aae0, 0xc42000d16a)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/file.go:124 +0xcd
github.com/goby-lang/goby/vm.(*thread).evalBuiltInMethod(0xc420155cb0, 0x460c540, 0xc4201eecc0, 0xc4201df120, 0x1, 0x0, 0x2, 0x0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:130 +0x202
github.com/goby-lang/goby/vm.glob..func21(0xc420155cb0, 0xc4201c5c00, 0xc42000d400, 0x2, 0x2)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/instruction.go:368 +0x3ea
github.com/goby-lang/goby/vm.(*thread).execInstruction(0xc420155cb0, 0xc4201c5c00, 0xc420258900)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:75 +0x96
github.com/goby-lang/goby/vm.(*thread).evalCallFrame(0xc420155cb0, 0xc4201c5c00)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:42 +0x60
github.com/goby-lang/goby/vm.(*thread).startFromTopFrame(0xc420155cb0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:36 +0x55
github.com/goby-lang/goby/vm.(*VM).startFromTopFrame(0xc42011e6c0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/vm.go:192 +0x2f
github.com/goby-lang/goby/vm.(*VM).REPLExec(0xc42011e6c0, 0xc4201a1700, 0x6, 0x8)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/repl.go:42 +0x64e
github.com/goby-lang/goby/igb.StartIgb(0x443fcc9, 0x5)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/igb/repl.go:218 +0x1606
main.main()
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/goby.go:27 +0x657
```

**Comment by st0012** [comment]
The first case is because that goby currently returns nothing ( not even nil) when assign variables 
And the second one is caused by the missing parens around file name I guess. Does this case works in ruby?

**Comment by hachi8833** [comment]
Yes, the following works in Ruby:

```ruby
[28] pry(main)> puts(a = 10)
10
=> nil
[29] pry(main)> puts(File.extname "test.gb")
.gb
=> nil
```

**Comment by st0012** [comment]
@Maxwell-Alexius I think the second error is related to parser, you can fix it if you want to play with parser more.
