### ISSUE TITLE
Bug: Top level capitalized method with parentheses causes panic

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#491]
```ruby
» def Hi
¤   42
» end
#»
» Hi
#» ERROR: NameError: uninitialized constant Hi. At REPL:1
» Hi()
panic: interface conversion: ast.Expression is *ast.Constant, not *ast.Identifier

goroutine 1 [running]:
github.com/goby-lang/goby/compiler/parser.(*Parser).parseCallExpressionWithoutReceiver(0xc42014e2d0, 0x4804240, 0xc4201ea3e0, 0x1, 0x0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/parser/method_call_parsing.go:9 +0x6c5
github.com/goby-lang/goby/compiler/parser.(*Parser).(github.com/goby-lang/goby/compiler/parser.parseCallExpressionWithoutReceiver)-fm(0x4804240, 0xc4201ea3e0, 0x4561357, 0x1)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/parser/parser.go:175 +0x3e
github.com/goby-lang/goby/compiler/parser.(*Parser).parseExpression(0xc42014e2d0, 0x2, 0x8, 0x18)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/parser/expression_parsing.go:149 +0xdf
github.com/goby-lang/goby/compiler/parser.(*Parser).parseExpressionStatement(0xc42014e2d0, 0x1)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/parser/statement_parsing.go:271 +0x146
github.com/goby-lang/goby/compiler/parser.(*Parser).parseStatement(0xc42014e2d0, 0x485a7e8, 0x1)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/parser/statement_parsing.go:28 +0x8a
github.com/goby-lang/goby/compiler/parser.(*Parser).ParseProgram(0xc42014e2d0, 0x4, 0xc420196fc0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/parser/parser.go:193 +0xe8
github.com/goby-lang/goby/igb.StartIgb(0x4561b7e, 0x5)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/igb/repl.go:160 +0x4d1
main.main()
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/goby.go:29 +0x954
```

I guess such capitalized methods on top-level should be prohibited.

FYI: capitalized methods other than top-level are prohibited, with/without parentheses:

```ruby
» class Foo
¤   def Hi
¤     49
¤   end
» end
#»
» Foo.new.Hi
expected next token to be IDENT, got CONSTANT instead. Line: 0
» Foo.new.Hi
» Foo.new.Hi()
expected next token to be IDENT, got CONSTANT instead. Line: 0
» Foo.new.Hi()
»
```

**Comment by st0012** [comment]
I think we should suspend all capitalized method call.
