### ISSUE TITLE
Nil groups make panic in MatchData

### ISSUE THREAD

**Issue by kachick** [goby-lang/goby#508]
- Your operating system: `sw_vers`
  - ProductName:    Mac OS X
  - ProductVersion: 10.13.1
  - BuildVersion:   17B48
- How did you install Goby: `go get github.com/goby-lang/goby`
- Goby version: 0.1.3
- The value of `$GOBY_ROOT`: /Users/kachick/gocode/src/github.com/goby-lang/goby

```ruby
'b'.match(Regexp.new('(a)?'))
```

```
panic: runtime error: index out of range
```

- Error messages

```
# goby -i
Goby 0.1.3 👺 🤠 😎
» 'b'.match(Regexp.new('(a)?'))
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/goby-lang/goby/vendor/github.com/dlclark/regexp2.(*Capture).String(...)
        /Users/kachick/gocode/src/github.com/goby-lang/goby/vm/match_data.go:123
github.com/goby-lang/goby/vm.(*VM).initMatchDataObject(0xc4200b42c0, 0xc4201da000, 0xc42019c094, 0x4, 0xc42019c048, 0x1, 0x0)
        /Users/kachick/gocode/src/github.com/goby-lang/goby/vm/match_data.go:123 +0x506
github.com/goby-lang/goby/vm.builtinStringInstanceMethods.func28.1(0xc4201360f0, 0xc42019e390, 0x1, 0x1, 0x0, 0xc42019e390, 0x0)
        /Users/kachick/gocode/src/github.com/goby-lang/goby/vm/string.go:1063 +0x107
github.com/goby-lang/goby/vm.(*thread).evalCallFrame(0xc4201360f0, 0x480d1c0, 0xc4201c2360)
        /Users/kachick/gocode/src/github.com/goby-lang/goby/vm/thread.go:63 +0x214
github.com/goby-lang/goby/vm.(*thread).startFromTopFrame(0xc4201360f0)
        /Users/kachick/gocode/src/github.com/goby-lang/goby/vm/thread.go:42 +0x61
github.com/goby-lang/goby/vm.(*thread).evalBuiltinMethod(0xc4201360f0, 0x480c8a0, 0xc4201c2200, 0xc4200ef980, 0x0, 0x1, 0xc4201be3c0, 0x0, 0x1, 0x4565223, ...)
        /Users/kachick/gocode/src/github.com/goby-lang/goby/vm/thread.go:240 +0x3f8
github.com/goby-lang/goby/vm.glob..func25(0xc4201360f0, 0x1, 0xc4201c21e0, 0xc42011c540, 0x4, 0x4)
        /Users/kachick/gocode/src/github.com/goby-lang/goby/vm/instruction.go:487 +0x4d1
github.com/goby-lang/goby/vm.(*thread).execInstruction(0xc4201360f0, 0xc4201c21e0, 0xc42011c580)
        /Users/kachick/gocode/src/github.com/goby-lang/goby/vm/thread.go:124 +0x70
github.com/goby-lang/goby/vm.(*thread).evalCallFrame(0xc4201360f0, 0x480d260, 0xc4201c21e0)
        /Users/kachick/gocode/src/github.com/goby-lang/goby/vm/thread.go:50 +0x38f
github.com/goby-lang/goby/vm.(*thread).startFromTopFrame(0xc4201360f0)
        /Users/kachick/gocode/src/github.com/goby-lang/goby/vm/thread.go:42 +0x61
github.com/goby-lang/goby/vm.(*VM).startFromTopFrame(0xc4200b42c0)
        /Users/kachick/gocode/src/github.com/goby-lang/goby/vm/vm.go:269 +0x2f
github.com/goby-lang/goby/vm.(*VM).REPLExec(0xc4200b42c0, 0xc4201c6008, 0x1, 0x1)
        /Users/kachick/gocode/src/github.com/goby-lang/goby/vm/repl.go:43 +0x78f
github.com/goby-lang/goby/igb.StartIgb(0x45654fb, 0x5)
        /Users/kachick/gocode/src/github.com/goby-lang/goby/igb/repl.go:230 +0xd23
main.main()
        /Users/kachick/gocode/src/github.com/goby-lang/goby/goby.go:29 +0x954
```

**Comment by hachi8833** [comment]
@saveriomiroddi While I checking the bug, I found that the following custom struct is used in `MatchData` struct:

```go
type MatchDataObject struct {
	*baseObj
	captures  []string
	positions []int
	pattern   string // original regex
	text      string // original text
}
```

I'd like to change the struct to the following, by using the existing [`*regexp.Match`](https://github.com/goby-lang/goby/blob/master/vendor/github.com/dlclark/regexp2/match.go#L11) 

```go
type Match = regexp2.Match
type MatchDataObject struct {
	*baseObj
	match *Match
}
```

The struct contains all attributes for regexp, including captures/position/pattern/text.
Actually, I tried the change locally, and confirmed it works fine and fixes the bug.

Is it OK for me to change as that?

**Comment by saveriomiroddi** [comment]
> Is it OK for me to change as those?

Absolutely. Good catch :laughing: I actually don't know how/why I missed that :smile:

**Comment by saveriomiroddi** [comment]
> In addition, I'd like to change the format of MatchData as follows, using 0: for the original text:
> Is it OK for me to change as those?

Regarding those, @st0012 should answer, as it's a matter of design choice. I've followed the Ruby standard, which makes sense - the group `0` is not an individual capturing group as the others, that's why it has no `0:` prefix.

**Comment by hachi8833** [comment]
@st0012 I'd send the PR if you're ok with `0:` prefix.

**Comment by kachick** [comment]
Thank you!
