### ISSUE TITLE
Bug: multiple assignment from implicit array causes panic

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#524]
The following works:

```ruby
» a, b, c = [1, 2, 3]
#» 3
» a
#» 1
» b
#» 2
» c
#» 3
```

The following causes panic:

```ruby
» a, b, c = 1, 2, 3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x40f1455]

goroutine 1 [running]:
github.com/goby-lang/goby/compiler/ast.(*BaseNode).MarkAsExp(0x0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/ast/ast.go:36 +0x5
github.com/goby-lang/goby/compiler/parser.(*Parser).parseStatement(0xc420138240, 0x486f768, 0x1)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/parser/statement_parsing.go:34 +0xbd
github.com/goby-lang/goby/compiler/parser.(*Parser).ParseProgram(0xc420138240, 0x11, 0xc42011e040)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/compiler/parser/parser.go:193 +0xe8
github.com/goby-lang/goby/igb.StartIgb(0x456d9c0, 0x5)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/igb/repl.go:160 +0x4d1
main.main()
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/goby.go:29 +0x954
```

FYI: works in Ruby:

```ruby
#ruby
i, j, k = 1, 2, 3
=> [1, 2, 3]
```

**Comment by hachi8833** [comment]
I found one more thing: Current Goby returns only the last element on multiple assignment:

```ruby
# Goby
» a, b, c = [1, 2, 3]
#» 3
» a = [1, 2, 3]
#» [1, 2, 3]
» x, y, z = *a
#» 3
```

Ruby returns an array:

```ruby
[8] pry(main)> a = [1,2,3]
=> [1, 2, 3]
[9] pry(main)> i, j, k = *a
=> [1, 2, 3]
```

Looks like this also should be changed.

**Comment by hachi8833** [comment]
I think we need more test for multiple assignment on evaluation_test.go.

I wrote the following for evaluation_test.go:

```go
func TestMultipleAssignmentEvaluation(t *testing.T) {
	tests := []struct {
		input         string
		expectedValue string
	}{
		{`
		a, b, c = ["x", "y", "z"]
		[a, b, c].to_s
		`, "[\"x\", \"y\", \"z\"]"},
		{`
		a, b, c = [1, 2, 3]
		[a, b, c].to_s
		`, "[1, 2, 3]"},
		{`
		a, b, c = [1, 2, 3, 4]
		[a, b, c].to_s
		`, "[1, 2, 3]"},
		{`
		a, b, c = [1, 2]
		[a, b, c].to_s
		`, "[1, 2, nil]"},
		{`
		a = [1, 2, 3]
		i, j, k = *a
		[i, j, k].to_s
		`, "[1, 2, 3]"},
		{`
		a = [1, 2]
		i, j, k = *a
		[i, j, k].to_s
		`, "[1, 2, nil]"},
		{`
		a = [1, 2, 3, 4]
		i, j, k = *a
		[i, j, k].to_s
		`, "[1, 2, 3]"},
		{`
		a = [{ m: 1, n:2 }, [3, 4]]
		i, j = *a
		[i, j].to_s
		`, "[{ m: 1, n: 2 }, [3, 4]]"},
		// FIXME
		{`
		a, b, c = 1, 2, 3
		[a, b, c].to_s
		`, "[1, 2, 3]"},
		{`
		a, b, c = 1, 2
		[a, b, c].to_s
		`, "[1, 2, nil]"},
		{`
		a, b, c = 1, 2, 3, 4
		[a, b, c].to_s
		`, "[1, 2, 3]"},
	}

	for i, tt := range tests {
		vm := initTestVM()
		evaluated := vm.testEval(t, tt.input, getFilename())
		testStringObject(t, i, evaluated, tt.expectedValue)
		vm.checkCFP(t, i, 0)
		vm.checkSP(t, i, 1)
	}
}
```

**Comment by hachi8833** [comment]
Perhaps this is related to https://github.com/goby-lang/goby/issues/444

**Comment by st0012** [comment]
@hachi8833 This and #444 are all parser's issue, but not directly related to each other I think.
And currently I don't want to support multiple variable assignment like:

```ruby
i, j, k = 1, 2, 3
=> [1, 2, 3]
```

So what we should do is to raise a parser error when users attempt to do something like this.

**Comment by ear7h** [comment]
I was looking into this today and I found it only happens with `* *`, not `**` or other operators. I think it's caused by the [registering of asterisk as a prefix expression](https://github.com/goby-lang/goby/blob/master/compiler/parser/parser.go#L69). 

Removing this line and adding the following seems to fix this specific issue, but running `go test ./...` yields several parser related test failures before a `SIGSEGV`. I'm willing to work on this but unsure how to proceed.

**Comment by hachi8833** [comment]
Thank you for looking into it!
Any suggestions to him? > @st0012

**Comment by st0012** [comment]
@hachi8833 @ear7h what issue are we talking about now? Can you give me code snippet and expected/actual output to help me catch up?

**Comment by ear7h** [comment]
@st0012 my bad I meant to reply to a different issue (#444) will move there...

**Comment by st0012** [comment]
@shes50103 Can you help on this, although this is more REPL related

**Comment by shes50103** [comment]
@st0012 ok, I will fix it!
