### ISSUE TITLE
Bug: uninitialized toplevel constant causes panic in REPL

### ISSUE THREAD

**Issue by hachi8833** [goby-lang/goby#528]
Looks like #475 causes the following.

Just entering an uninitialized constant on toplevel in REPL causes panic:

```ruby
Goby 0.1.3 😶 😆 😏
» Bar
panic: NameError: uninitialized constant Bar
from REPL:1 [recovered]
	panic: (*vm.Error) (0x4535220,0xc4201ac0a0)

goroutine 1 [running]:
github.com/goby-lang/goby/vm.(*thread).reportErrorAndStop(0xc42008b3b0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:121 +0x398
github.com/goby-lang/goby/vm.(*thread).evalCallFrame.func1(0xc42008b3b0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:48 +0x4d
panic(0x44bdea0, 0xc420198120)
	/usr/local/opt/go/libexec/src/runtime/panic.go:491 +0x283
github.com/goby-lang/goby/vm.(*thread).pushErrorObject(0xc42008b3b0, 0x456e52d, 0x9, 0x1, 0x4575dce, 0x19, 0xc420167698, 0x1, 0x1)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:342 +0x16b
github.com/goby-lang/goby/vm.glob..func5(0xc42008b3b0, 0x1, 0xc4201aa0a0, 0xc4201aa080, 0x2, 0x2)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/instruction.go:78 +0x252
github.com/goby-lang/goby/vm.(*thread).execInstruction(0xc42008b3b0, 0xc4201aa0a0, 0xc420192180)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:135 +0x70
github.com/goby-lang/goby/vm.(*thread).evalCallFrame(0xc42008b3b0, 0x4819260, 0xc4201aa0a0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:56 +0xde
github.com/goby-lang/goby/vm.(*thread).startFromTopFrame(0xc42008b3b0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/thread.go:42 +0x61
github.com/goby-lang/goby/vm.(*VM).startFromTopFrame(0xc4200c42c0)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/vm.go:279 +0x2f
github.com/goby-lang/goby/vm.(*VM).REPLExec(0xc4200c42c0, 0xc4201b0008, 0x1, 0x1)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/vm/repl.go:44 +0x7ee
github.com/goby-lang/goby/igb.StartIgb(0x456cafc, 0x5)
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/igb/repl.go:230 +0xd23
main.main()
	/Users/hachi8833/deve/golang/gopath/sys/src/github.com/goby-lang/goby/goby.go:29 +0x954
```

The previous [dbe45c](https://github.com/goby-lang/goby/commit/dbe45c1225bc646b4e1fa0dfb6b5911500b786df) works:

```ruby
Goby 0.1.3 🤥 🤥 👺
» Bar
#» ERROR: NameError: uninitialized constant Bar. At REPL:1
```

**Comment by st0012** [comment]
@hachi8833 I'll fix that later. And it looks like we'll need some error tests for REPL mode's VM now 😂

**Comment by hachi8833** [comment]
Just now I found a useful info https://stackoverflow.com/questions/37256859/how-can-i-write-a-go-test-that-writes-to-stdin
I'd try writing tests for REPL.

**Comment by st0012** [comment]
For this issue, it should be the VM's problem. And you should be able to reproduce it in [this test function](https://github.com/goby-lang/goby/blob/master/vm/vm_test.go#L21). But I also support writing a full integration test for REPL.

**Comment by hachi8833** [comment]
Now the top-level errors echoes twice, on the current master branch.

```ruby
» Rat
NameError: uninitialized constant Rat
from REPL:1
#» NameError: uninitialized constant Rat
from REPL:1
```

**Comment by st0012** [comment]
Fixed

**Comment by hachi8833** [comment]
Works fine now!

```ruby
» Bar
#» NameError: uninitialized constant Bar
from REPL:1
```
