### ISSUE TITLE
Including an Array causes an internal error

### ISSUE THREAD

**Issue by saveriomiroddi** [goby-lang/goby#640]
The following code causes an internal error and subsequent panic:

```ruby
» class TestClass
¤   include []
» end
interface conversion: vm.Object is *vm.RClass, not *vm.Error
#» UndefinedMethodError: Undefined Method '[]' for TestClass
» exit
interface conversion: vm.Object is nil, not *vm.Error
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0xa4b5b4]

goroutine 1 [running]:
github.com/goby-lang/goby/vm.(*VM).GetREPLResult(0xc420092820, 0xc4201fa540, 0x3)
  /path/to/go/src/github.com/goby-lang/goby/vm/repl.go:73 +0x44
github.com/goby-lang/goby/igb.StartIgb(0xbd6b78, 0x7)
  /path/to/go/src/github.com/goby-lang/goby/igb/repl.go:227 +0xd18
main.main()
  /path/to/go/src/github.com/goby-lang/goby/goby.go:29 +0xbaa
```

**Comment by st0012** [comment]
I think that's because the way we return/retrieve value at the wrong stack position.
@SD10 this is something related to incorrect stack operation, which you might be interested in tracking of.
